/* Generated by Pyrex 0.9.8.5 on Thu Feb 25 17:15:16 2010 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "stdlib.h"
#include "stdint.h"
#include "../src/capi.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from fastbit */


/* Declarations from implementation of fastbit */

struct __pyx_obj_7fastbit_Query {
  PyObject_HEAD
  struct FastBitQuery *qh;
};


static PyTypeObject *__pyx_ptype_7fastbit_Query = 0;

static char __pyx_k1[] = "cleanup";
static char __pyx_k2[] = "destroy_query";
static char __pyx_k3[] = "get_select_clause";
static char __pyx_k4[] = "strip";
static char __pyx_k5[] = "";
static char __pyx_k6[] = "count(*)";
static char __pyx_k7[] = "get_from_clause";
static char __pyx_k8[] = "get_where_clause";
static char __pyx_k9[] = "Query(SELECT \"%s\" FROM \"%s\" WHERE (%s))";
static char __pyx_k10[] = "get_result_rows";
static char __pyx_k11[] = "FastBit";
static char __pyx_k12[] = "__init__";
static char __pyx_k13[] = "__del__";
static char __pyx_k14[] = "add_values";
static char __pyx_k15[] = "build_index";
static char __pyx_k16[] = "build_indexes";
static char __pyx_k17[] = "columns_in_partition";
static char __pyx_k18[] = "rows_in_partition";
static char __pyx_k19[] = "flush_buffer";
static char __pyx_k20[] = "get_logfile";
static char __pyx_k21[] = "set_logfile";
static char __pyx_k22[] = "get_verbose_level";
static char __pyx_k23[] = "set_verbose_level";
static char __pyx_k24[] = "purge_index";
static char __pyx_k25[] = "purge_indexes";

static PyObject *__pyx_n_FastBit;
static PyObject *__pyx_n___del__;
static PyObject *__pyx_n___init__;
static PyObject *__pyx_n_add_values;
static PyObject *__pyx_n_build_index;
static PyObject *__pyx_n_build_indexes;
static PyObject *__pyx_n_cleanup;
static PyObject *__pyx_n_columns_in_partition;
static PyObject *__pyx_n_destroy_query;
static PyObject *__pyx_n_flush_buffer;
static PyObject *__pyx_n_get_from_clause;
static PyObject *__pyx_n_get_logfile;
static PyObject *__pyx_n_get_result_rows;
static PyObject *__pyx_n_get_select_clause;
static PyObject *__pyx_n_get_verbose_level;
static PyObject *__pyx_n_get_where_clause;
static PyObject *__pyx_n_purge_index;
static PyObject *__pyx_n_purge_indexes;
static PyObject *__pyx_n_rows_in_partition;
static PyObject *__pyx_n_set_logfile;
static PyObject *__pyx_n_set_verbose_level;
static PyObject *__pyx_n_strip;

static PyObject *__pyx_k5p;
static PyObject *__pyx_k6p;
static PyObject *__pyx_k9p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_FastBit, 1, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_n___del__, 1, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_n___init__, 1, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_n_add_values, 1, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_n_build_index, 1, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_n_build_indexes, 1, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_n_cleanup, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_columns_in_partition, 1, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_n_destroy_query, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n_flush_buffer, 1, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_n_get_from_clause, 1, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_n_get_logfile, 1, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_n_get_result_rows, 1, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_n_get_select_clause, 1, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_n_get_verbose_level, 1, __pyx_k22, sizeof(__pyx_k22)},
  {&__pyx_n_get_where_clause, 1, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_n_purge_index, 1, __pyx_k24, sizeof(__pyx_k24)},
  {&__pyx_n_purge_indexes, 1, __pyx_k25, sizeof(__pyx_k25)},
  {&__pyx_n_rows_in_partition, 1, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_n_set_logfile, 1, __pyx_k21, sizeof(__pyx_k21)},
  {&__pyx_n_set_verbose_level, 1, __pyx_k23, sizeof(__pyx_k23)},
  {&__pyx_n_strip, 1, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k5p, 0, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_k6p, 0, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_k9p, 0, __pyx_k9, sizeof(__pyx_k9)},
  {0, 0, 0, 0}
};

static PyObject *__pyx_d1;


/* Implementation of fastbit */

static PyObject *__pyx_f_7fastbit_7FastBit___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_7FastBit___init__[] = "May pass in None as rcfile if one is expected to use use the \ndefault configuartion files listed in the documentation of \nibis::resources::read. One may call this function multiple times \nto read multiple configuration files to modify the parameters.";
static PyMethodDef __pyx_mdef_7fastbit_7FastBit___init__ = {"__init__", (PyCFunction)__pyx_f_7fastbit_7FastBit___init__, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_7FastBit___init__};
static PyObject *__pyx_f_7fastbit_7FastBit___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_rcfile = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  char *__pyx_2;
  static char *__pyx_argnames[] = {"self","rcfile",0};
  __pyx_v_rcfile = __pyx_d1;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_self, &__pyx_v_rcfile)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_rcfile);
  __pyx_1 = PyObject_IsTrue(__pyx_v_rcfile); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  if (__pyx_1) {
    __pyx_2 = PyString_AsString(__pyx_v_rcfile); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
    fastbit_init(__pyx_2);
    goto __pyx_L2;
  }
  /*else*/ {
    fastbit_init(NULL);
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("fastbit.FastBit.__init__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_rcfile);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_7FastBit___del__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_7fastbit_7FastBit___del__ = {"__del__", (PyCFunction)__pyx_f_7fastbit_7FastBit___del__, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_7fastbit_7FastBit___del__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"self",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_self)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_cleanup); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("fastbit.FastBit.__del__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_7FastBit_add_values(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_7FastBit_add_values[] = "add_values(self, colname, coltype, vals, start)\n\nAdd values of the specified column (colname) to the in-memory buffer.\n \n  colname Name of the column. Must start with an alphabet and \n   followed by a combination of alphanumerical characters. Following \n   the SQL standard, the column name is not case sensitive.\n  coltype The type of the values for the column. The support types \n   are: \"double\", \"float\", \"long\", \"int\", \"short\", \"byte\", \"ulong\", \n   \"uint\", \"ushort\", and \"ubyte\". Only the first non-space character \n   is checked for the first six types and only the first two characters \n   are checked for the remaining types. This string is not case sensitive.\n  vals The array containing the values. \n  start The position (row number) of the first element of the array. \n   Normally, this argument is zero (0) if all values are valid. One may \n   use this argument to skip some rows and indicate to FastBit that the \n   skipped rows contain NULL values.";
static PyMethodDef __pyx_mdef_7fastbit_7FastBit_add_values = {"add_values", (PyCFunction)__pyx_f_7fastbit_7FastBit_add_values, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_7FastBit_add_values};
static PyObject *__pyx_f_7fastbit_7FastBit_add_values(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_colname = 0;
  PyObject *__pyx_v_coltype = 0;
  PyObject *__pyx_v_vals = 0;
  PyObject *__pyx_v_start = 0;
  PyObject *__pyx_r;
  char *__pyx_1;
  char *__pyx_2;
  Py_ssize_t __pyx_3;
  uint32_t __pyx_4;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"self","colname","coltype","vals","start",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOOO", __pyx_argnames, &__pyx_v_self, &__pyx_v_colname, &__pyx_v_coltype, &__pyx_v_vals, &__pyx_v_start)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_colname);
  Py_INCREF(__pyx_v_coltype);
  Py_INCREF(__pyx_v_vals);
  Py_INCREF(__pyx_v_start);
  __pyx_1 = PyString_AsString(__pyx_v_colname); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  __pyx_2 = PyString_AsString(__pyx_v_coltype); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  __pyx_3 = PyObject_Length(__pyx_v_vals); if (__pyx_3 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  __pyx_4 = PyInt_AsUnsignedLongMask(__pyx_v_start); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(fastbit_add_values(__pyx_1,__pyx_2,((void *)__pyx_v_vals),__pyx_3,__pyx_4)); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  __pyx_r = __pyx_5;
  __pyx_5 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("fastbit.FastBit.add_values");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_colname);
  Py_DECREF(__pyx_v_coltype);
  Py_DECREF(__pyx_v_vals);
  Py_DECREF(__pyx_v_start);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_7FastBit_build_index(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_7FastBit_build_index[] = "build_index(self, indexLocation, cname)\n\nBuild an index for the named attribute. ";
static PyMethodDef __pyx_mdef_7fastbit_7FastBit_build_index = {"build_index", (PyCFunction)__pyx_f_7fastbit_7FastBit_build_index, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_7FastBit_build_index};
static PyObject *__pyx_f_7fastbit_7FastBit_build_index(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_indexLocation = 0;
  PyObject *__pyx_v_cname = 0;
  PyObject *__pyx_r;
  char *__pyx_1;
  char *__pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"self","indexLocation","cname",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_self, &__pyx_v_indexLocation, &__pyx_v_cname)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_indexLocation);
  Py_INCREF(__pyx_v_cname);
  __pyx_1 = PyString_AsString(__pyx_v_indexLocation); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_2 = PyString_AsString(__pyx_v_cname); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(fastbit_build_index(__pyx_1,__pyx_2,NULL)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("fastbit.FastBit.build_index");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_indexLocation);
  Py_DECREF(__pyx_v_cname);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_7FastBit_build_indexes(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_7FastBit_build_indexes[] = "build_indexes(self, indexLocation, indexOptions)\n\nBuild indexes for all columns in the named directory. ";
static PyMethodDef __pyx_mdef_7fastbit_7FastBit_build_indexes = {"build_indexes", (PyCFunction)__pyx_f_7fastbit_7FastBit_build_indexes, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_7FastBit_build_indexes};
static PyObject *__pyx_f_7fastbit_7FastBit_build_indexes(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_indexLocation = 0;
  PyObject *__pyx_v_indexOptions = 0;
  PyObject *__pyx_r;
  char *__pyx_1;
  char *__pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"self","indexLocation","indexOptions",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_self, &__pyx_v_indexLocation, &__pyx_v_indexOptions)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_indexLocation);
  Py_INCREF(__pyx_v_indexOptions);
  __pyx_1 = PyString_AsString(__pyx_v_indexLocation); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
  __pyx_2 = PyString_AsString(__pyx_v_indexOptions); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(fastbit_build_indexes(__pyx_1,__pyx_2)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("fastbit.FastBit.build_indexes");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_indexLocation);
  Py_DECREF(__pyx_v_indexOptions);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_7FastBit_cleanup(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_7FastBit_cleanup[] = "cleanup(self)\n\nClean up resources hold by FastBit file manager.";
static PyMethodDef __pyx_mdef_7fastbit_7FastBit_cleanup = {"cleanup", (PyCFunction)__pyx_f_7fastbit_7FastBit_cleanup, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_7FastBit_cleanup};
static PyObject *__pyx_f_7fastbit_7FastBit_cleanup(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {"self",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_self)) return 0;
  Py_INCREF(__pyx_v_self);
  fastbit_cleanup();

  __pyx_r = Py_None; Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_7FastBit_columns_in_partition(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_7FastBit_columns_in_partition[] = "columns_in_partition(self, datadir)\n\nReturn the number of columns in the data partition. ";
static PyMethodDef __pyx_mdef_7fastbit_7FastBit_columns_in_partition = {"columns_in_partition", (PyCFunction)__pyx_f_7fastbit_7FastBit_columns_in_partition, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_7FastBit_columns_in_partition};
static PyObject *__pyx_f_7fastbit_7FastBit_columns_in_partition(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_datadir = 0;
  PyObject *__pyx_r;
  char *__pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"self","datadir",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_self, &__pyx_v_datadir)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_datadir);
  __pyx_1 = PyString_AsString(__pyx_v_datadir); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(fastbit_columns_in_partition(__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("fastbit.FastBit.columns_in_partition");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_datadir);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_7FastBit_rows_in_partition(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_7FastBit_rows_in_partition[] = "rows_in_partition(self, datadir)\n\nReturn the number of rows in the data partition. ";
static PyMethodDef __pyx_mdef_7fastbit_7FastBit_rows_in_partition = {"rows_in_partition", (PyCFunction)__pyx_f_7fastbit_7FastBit_rows_in_partition, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_7FastBit_rows_in_partition};
static PyObject *__pyx_f_7fastbit_7FastBit_rows_in_partition(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_datadir = 0;
  PyObject *__pyx_r;
  char *__pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"self","datadir",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_self, &__pyx_v_datadir)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_datadir);
  __pyx_1 = PyString_AsString(__pyx_v_datadir); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(fastbit_rows_in_partition(__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("fastbit.FastBit.rows_in_partition");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_datadir);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_7FastBit_flush_buffer(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_7FastBit_flush_buffer[] = "flush_buffer(self, datadir)\n\nFlush the in-memory data to the named directory. \n\nIn addition, if the new records contain columns that are not already \nin the directory, then the new columns are automatically added with \nexisting records assumed to contain NULL values. This set of functions \nare intended for a user to append some number of rows in one operation. \nIt is clear that writing one row as a time is slow because of the \noverhead involved in writing the files. On the other hand, since the \nnew rows are stored in memory, it can not store too many rows.";
static PyMethodDef __pyx_mdef_7fastbit_7FastBit_flush_buffer = {"flush_buffer", (PyCFunction)__pyx_f_7fastbit_7FastBit_flush_buffer, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_7FastBit_flush_buffer};
static PyObject *__pyx_f_7fastbit_7FastBit_flush_buffer(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_datadir = 0;
  PyObject *__pyx_r;
  char *__pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"self","datadir",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_self, &__pyx_v_datadir)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_datadir);
  __pyx_1 = PyString_AsString(__pyx_v_datadir); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(fastbit_flush_buffer(__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("fastbit.FastBit.flush_buffer");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_datadir);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_7FastBit_get_logfile(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_7FastBit_get_logfile[] = "get_logfile(self)\n\nFind out the name of the current log file. ";
static PyMethodDef __pyx_mdef_7fastbit_7FastBit_get_logfile = {"get_logfile", (PyCFunction)__pyx_f_7fastbit_7FastBit_get_logfile, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_7FastBit_get_logfile};
static PyObject *__pyx_f_7fastbit_7FastBit_get_logfile(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"self",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_self)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyString_FromString(fastbit_get_logfile()); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("fastbit.FastBit.get_logfile");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_7FastBit_set_logfile(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_7FastBit_set_logfile[] = "set_logfile(self, filename)\n\nChange the name of the log file. A blank string indicates stdout.";
static PyMethodDef __pyx_mdef_7fastbit_7FastBit_set_logfile = {"set_logfile", (PyCFunction)__pyx_f_7fastbit_7FastBit_set_logfile, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_7FastBit_set_logfile};
static PyObject *__pyx_f_7fastbit_7FastBit_set_logfile(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_filename = 0;
  PyObject *__pyx_r;
  char *__pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"self","filename",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_self, &__pyx_v_filename)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_filename);
  __pyx_1 = PyString_AsString(__pyx_v_filename); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(fastbit_set_logfile(__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("fastbit.FastBit.set_logfile");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_filename);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_7FastBit_get_verbose_level(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_7FastBit_get_verbose_level[] = "get_verbose_level(self)\n\nReturn the current verboseness level. ";
static PyMethodDef __pyx_mdef_7fastbit_7FastBit_get_verbose_level = {"get_verbose_level", (PyCFunction)__pyx_f_7fastbit_7FastBit_get_verbose_level, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_7FastBit_get_verbose_level};
static PyObject *__pyx_f_7fastbit_7FastBit_get_verbose_level(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"self",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_self)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyInt_FromLong(fastbit_get_verbose_level()); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 188; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("fastbit.FastBit.get_verbose_level");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_7FastBit_set_verbose_level(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_7FastBit_set_verbose_level[] = "set_verbose_level(self, v)\n\nChange the verboseness of FastBit functions. ";
static PyMethodDef __pyx_mdef_7fastbit_7FastBit_set_verbose_level = {"set_verbose_level", (PyCFunction)__pyx_f_7fastbit_7FastBit_set_verbose_level, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_7FastBit_set_verbose_level};
static PyObject *__pyx_f_7fastbit_7FastBit_set_verbose_level(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_v = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"self","v",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_self, &__pyx_v_v)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_v);
  __pyx_1 = PyInt_AsLong(__pyx_v_v); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(fastbit_set_verbose_level(__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("fastbit.FastBit.set_verbose_level");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_v);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_7FastBit_purge_index(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_7FastBit_purge_index[] = "purge_index(self, indexLocation, cname)\n\nPurge the index of the named attribute. ";
static PyMethodDef __pyx_mdef_7fastbit_7FastBit_purge_index = {"purge_index", (PyCFunction)__pyx_f_7fastbit_7FastBit_purge_index, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_7FastBit_purge_index};
static PyObject *__pyx_f_7fastbit_7FastBit_purge_index(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_indexLocation = 0;
  PyObject *__pyx_v_cname = 0;
  PyObject *__pyx_r;
  char *__pyx_1;
  char *__pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"self","indexLocation","cname",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_self, &__pyx_v_indexLocation, &__pyx_v_cname)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_indexLocation);
  Py_INCREF(__pyx_v_cname);
  __pyx_1 = PyString_AsString(__pyx_v_indexLocation); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
  __pyx_2 = PyString_AsString(__pyx_v_cname); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(fastbit_purge_index(__pyx_1,__pyx_2)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("fastbit.FastBit.purge_index");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_indexLocation);
  Py_DECREF(__pyx_v_cname);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_7FastBit_purge_indexes(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_7FastBit_purge_indexes[] = "purge_indexes(self, indexLocation)\n\nPurge all index files. ";
static PyMethodDef __pyx_mdef_7fastbit_7FastBit_purge_indexes = {"purge_indexes", (PyCFunction)__pyx_f_7fastbit_7FastBit_purge_indexes, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_7FastBit_purge_indexes};
static PyObject *__pyx_f_7fastbit_7FastBit_purge_indexes(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_indexLocation = 0;
  PyObject *__pyx_r;
  char *__pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"self","indexLocation",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_self, &__pyx_v_indexLocation)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_indexLocation);
  __pyx_1 = PyString_AsString(__pyx_v_indexLocation); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(fastbit_purge_indexes(__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("fastbit.FastBit.purge_indexes");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_indexLocation);
  return __pyx_r;
}

static int __pyx_f_7fastbit_5Query___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_7fastbit_5Query___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_selectClause;
  char *__pyx_v_indexLocation;
  char *__pyx_v_queryConditions;
  int __pyx_r;
  static char *__pyx_argnames[] = {"selectClause","indexLocation","queryConditions",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "sss", __pyx_argnames, &__pyx_v_selectClause, &__pyx_v_indexLocation, &__pyx_v_queryConditions)) return -1;
  Py_INCREF(__pyx_v_self);
  ((struct __pyx_obj_7fastbit_Query *)__pyx_v_self)->qh = fastbit_build_query(__pyx_v_selectClause,__pyx_v_indexLocation,__pyx_v_queryConditions);

  __pyx_r = 0;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_5Query___del__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_7fastbit_5Query___del__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_destroy_query); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 218; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 218; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("fastbit.Query.__del__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_5Query___repr__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_7fastbit_5Query___repr__(PyObject *__pyx_v_self) {
  PyObject *__pyx_v_select;
  PyObject *__pyx_v_from_clause;
  PyObject *__pyx_v_where;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  Py_INCREF(__pyx_v_self);
  __pyx_v_select = Py_None; Py_INCREF(Py_None);
  __pyx_v_from_clause = Py_None; Py_INCREF(Py_None);
  __pyx_v_where = Py_None; Py_INCREF(Py_None);

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":221 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_get_select_clause); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 221; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 221; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_select);
  __pyx_v_select = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":222 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_select, __pyx_n_strip); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 222; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 222; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_Cmp(__pyx_2, __pyx_k5p, &__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 222; goto __pyx_L1;}
  __pyx_3 = __pyx_3 == 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (__pyx_3) {
    Py_INCREF(__pyx_k6p);
    Py_DECREF(__pyx_v_select);
    __pyx_v_select = __pyx_k6p;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":223 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_get_from_clause); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 223; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 223; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_from_clause);
  __pyx_v_from_clause = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":224 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_get_where_clause); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_where);
  __pyx_v_where = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":225 */
  __pyx_1 = PyTuple_New(3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 225; goto __pyx_L1;}
  Py_INCREF(__pyx_v_select);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_select);
  Py_INCREF(__pyx_v_from_clause);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_from_clause);
  Py_INCREF(__pyx_v_where);
  PyTuple_SET_ITEM(__pyx_1, 2, __pyx_v_where);
  __pyx_2 = PyNumber_Remainder(__pyx_k9p, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 225; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("fastbit.Query.__repr__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_select);
  Py_DECREF(__pyx_v_from_clause);
  Py_DECREF(__pyx_v_where);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static Py_ssize_t __pyx_f_7fastbit_5Query___len__(PyObject *__pyx_v_self); /*proto*/
static Py_ssize_t __pyx_f_7fastbit_5Query___len__(PyObject *__pyx_v_self) {
  Py_ssize_t __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  Py_ssize_t __pyx_3;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_get_result_rows); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 227; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 227; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = PyInt_AsSsize_t(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 227; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_r = __pyx_3;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("fastbit.Query.__len__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_5Query_destroy_query(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_5Query_destroy_query[] = "destroy_query(self)\n\nFree all resource associated with the handle. ";
static PyObject *__pyx_f_7fastbit_5Query_destroy_query(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  fastbit_destroy_query(((struct __pyx_obj_7fastbit_Query *)__pyx_v_self)->qh);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_5Query_get_from_clause(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_5Query_get_from_clause[] = "get_from_clause(self)\n\nReturn the table name. ";
static PyObject *__pyx_f_7fastbit_5Query_get_from_clause(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyString_FromString(fastbit_get_from_clause(((struct __pyx_obj_7fastbit_Query *)__pyx_v_self)->qh)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 239; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("fastbit.Query.get_from_clause");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_5Query_get_where_clause(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_5Query_get_where_clause[] = "get_where_clause(self)\n\nReturn the query conditions. ";
static PyObject *__pyx_f_7fastbit_5Query_get_where_clause(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyString_FromString(fastbit_get_where_clause(((struct __pyx_obj_7fastbit_Query *)__pyx_v_self)->qh)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 245; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("fastbit.Query.get_where_clause");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_5Query_get_result_columns(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_5Query_get_result_columns[] = "get_result_columns(self)\n\nCount the number of columns selected in the select clause of the query. ";
static PyObject *__pyx_f_7fastbit_5Query_get_result_columns(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyInt_FromLong(fastbit_get_result_columns(((struct __pyx_obj_7fastbit_Query *)__pyx_v_self)->qh)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 251; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("fastbit.Query.get_result_columns");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_5Query_get_result_rows(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_5Query_get_result_rows[] = "get_result_rows(self)\n\nReturn the number of hits in the query. ";
static PyObject *__pyx_f_7fastbit_5Query_get_result_rows(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyInt_FromLong(fastbit_get_result_rows(((struct __pyx_obj_7fastbit_Query *)__pyx_v_self)->qh)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 257; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("fastbit.Query.get_result_rows");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_7fastbit_5Query_get_select_clause(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7fastbit_5Query_get_select_clause[] = "get_select_clause(self)\n\nReturn the string form of the select clause. ";
static PyObject *__pyx_f_7fastbit_5Query_get_select_clause(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyString_FromString(fastbit_get_select_clause(((struct __pyx_obj_7fastbit_Query *)__pyx_v_self)->qh)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 263; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("fastbit.Query.get_select_clause");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_tp_new_7fastbit_Query(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  if (__pyx_f_7fastbit_5Query___cinit__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_7fastbit_Query(PyObject *o) {
  (*o->ob_type->tp_free)(o);
}

static struct PyMethodDef __pyx_methods_7fastbit_Query[] = {
  {"__del__", (PyCFunction)__pyx_f_7fastbit_5Query___del__, METH_VARARGS|METH_KEYWORDS, 0},
  {"destroy_query", (PyCFunction)__pyx_f_7fastbit_5Query_destroy_query, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_5Query_destroy_query},
  {"get_from_clause", (PyCFunction)__pyx_f_7fastbit_5Query_get_from_clause, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_5Query_get_from_clause},
  {"get_where_clause", (PyCFunction)__pyx_f_7fastbit_5Query_get_where_clause, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_5Query_get_where_clause},
  {"get_result_columns", (PyCFunction)__pyx_f_7fastbit_5Query_get_result_columns, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_5Query_get_result_columns},
  {"get_result_rows", (PyCFunction)__pyx_f_7fastbit_5Query_get_result_rows, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_5Query_get_result_rows},
  {"get_select_clause", (PyCFunction)__pyx_f_7fastbit_5Query_get_select_clause, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7fastbit_5Query_get_select_clause},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Query = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_Query = {
  __pyx_f_7fastbit_5Query___len__, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Query = {
  __pyx_f_7fastbit_5Query___len__, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Query = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_7fastbit_Query = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "fastbit.Query", /*tp_name*/
  sizeof(struct __pyx_obj_7fastbit_Query), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_7fastbit_Query, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  __pyx_f_7fastbit_5Query___repr__, /*tp_repr*/
  &__pyx_tp_as_number_Query, /*tp_as_number*/
  &__pyx_tp_as_sequence_Query, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Query, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Query, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_7fastbit_Query, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_7fastbit_Query, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initfastbit(void); /*proto*/
PyMODINIT_FUNC initfastbit(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("fastbit", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyType_Ready(&__pyx_type_7fastbit_Query) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Query", (PyObject *)&__pyx_type_7fastbit_Query) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  __pyx_ptype_7fastbit_Query = &__pyx_type_7fastbit_Query;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":94 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_3 = __Pyx_CreateClass(__pyx_2, __pyx_1, __pyx_n_FastBit, "fastbit"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":95 */
  Py_INCREF(Py_None);
  __pyx_d1 = Py_None;
  __pyx_2 = PyCFunction_New(&__pyx_mdef_7fastbit_7FastBit___init__, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n___init__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":104 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_7fastbit_7FastBit___del__, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n___del__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":107 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_7fastbit_7FastBit_add_values, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_add_values, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":127 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_7fastbit_7FastBit_build_index, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_build_index, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":133 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_7fastbit_7FastBit_build_indexes, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_build_indexes, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":140 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_7fastbit_7FastBit_cleanup, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_cleanup, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":146 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_7fastbit_7FastBit_columns_in_partition, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_columns_in_partition, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":152 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_7fastbit_7FastBit_rows_in_partition, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_rows_in_partition, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":158 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_7fastbit_7FastBit_flush_buffer, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_flush_buffer, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":172 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_7fastbit_7FastBit_get_logfile, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_get_logfile, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":178 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_7fastbit_7FastBit_set_logfile, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_set_logfile, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":184 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_7fastbit_7FastBit_get_verbose_level, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 184; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 184; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_get_verbose_level, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 184; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":190 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_7fastbit_7FastBit_set_verbose_level, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_set_verbose_level, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":196 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_7fastbit_7FastBit_purge_index, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_purge_index, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":202 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_7fastbit_7FastBit_purge_indexes, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_purge_indexes, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_FastBit, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/jose/code/pyfastbit/pyfastbit/fastbit.pyx":259 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("fastbit");
}

static char *__pyx_filenames[] = {
  "fastbit.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
